package config

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"
)

const DefaultFile = `# Generated by DockerUpBot on first start.
# Secrets come from environment / .env — do not put tokens here.
# Listen address is set by the image (HTTP_ADDR=:9467).
data_path: /data/dockerupbot.json
refresh_seconds: 2
health_timeout_seconds: 120
notify_empty_scan: true
diun_container: diun
`

type Config struct {
	HTTPAddr          string
	WebhookSecret     string
	DataPath          string
	Update            UpdateConfig
	Telegram          TelegramConfig
	NotifyEmptyScan   bool
	DiunContainer     string
	SkipImages        []string // substring or regex (/re/)
	SkipContainers    []string
	QuietHours        string // "HH:MM-HH:MM" or empty
	PruneAfterSuccess bool
	RequireHealthy    bool // if true, bare "running" is not enough
}

type UpdateConfig struct {
	RefreshSeconds       int
	HealthTimeoutSeconds int
	ComposeRoot          string
}

type TelegramConfig struct {
	Token          string
	AllowedUsers   []int64
	ChatID         int64
	RefreshSeconds int
}

func EnsureDefault(path string) error {
	st, err := os.Stat(path)
	if err == nil {
		if !st.IsDir() {
			return nil
		}
		entries, readErr := os.ReadDir(path)
		if readErr != nil {
			return fmt.Errorf("%s is a directory and cannot be read: %w", path, readErr)
		}
		if len(entries) > 0 {
			return fmt.Errorf("%s is a non-empty directory; delete it on the host (rm -rf %s) then restart", path, path)
		}
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("%s is a directory and could not be removed: %w; run: rm -rf ./config.yml ./config", path, err)
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0750); err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(DefaultFile), 0640); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}

func Load(path string) (Config, error) {
	if err := EnsureDefault(path); err != nil {
		return Config{}, err
	}
	b, err := os.ReadFile(path)
	if err != nil {
		return Config{}, err
	}
	c := Config{
		HTTPAddr:      ":9467",
		DataPath:      "/data/dockerupbot.json",
		DiunContainer: "diun",
		Update: UpdateConfig{
			RefreshSeconds:       2,
			HealthTimeoutSeconds: 120,
		},
	}
	for _, line := range strings.Split(string(b), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "-") {
			continue
		}
		p := strings.SplitN(line, ":", 2)
		if len(p) != 2 {
			continue
		}
		k, v := strings.TrimSpace(p[0]), strings.TrimSpace(strings.Trim(strings.TrimSpace(p[1]), "\"'"))
		switch k {
		case "http_addr":
			c.HTTPAddr = v
		case "webhook_secret":
			c.WebhookSecret = v
		case "data_path":
			c.DataPath = v
		case "compose_root":
			c.Update.ComposeRoot = v
		case "refresh_seconds":
			if n, e := strconv.Atoi(v); e == nil {
				c.Update.RefreshSeconds = n
				c.Telegram.RefreshSeconds = n
			}
		case "health_timeout_seconds":
			if n, e := strconv.Atoi(v); e == nil {
				c.Update.HealthTimeoutSeconds = n
			}
		case "telegram_token":
			c.Telegram.Token = v
		case "telegram_chat_id":
			if n, e := strconv.ParseInt(v, 10, 64); e == nil {
				c.Telegram.ChatID = n
			}
		case "telegram_allowed_users", "allowed_users":
			c.Telegram.AllowedUsers = parseIntList(v)
		case "notify_empty_scan":
			c.NotifyEmptyScan = parseBool(v)
		case "diun_container":
			if v != "" {
				c.DiunContainer = v
			}
		case "skip_images":
			c.SkipImages = parseCSV(v)
		case "skip_containers":
			c.SkipContainers = parseCSV(v)
		case "quiet_hours":
			c.QuietHours = v
		case "prune_after_success":
			c.PruneAfterSuccess = parseBool(v)
		case "require_healthy":
			c.RequireHealthy = parseBool(v)
		}
	}

	if x := firstEnv("TELEGRAM_TOKEN", "TELEGRAM_BOT_TOKEN"); x != "" {
		c.Telegram.Token = x
	}
	if x := firstEnv("HTTP_ADDR", "DOCKERUPBOT_HTTP_ADDR"); x != "" {
		c.HTTPAddr = x
	}
	if x := firstEnv("WEBHOOK_SECRET", "DOCKERUPBOT_WEBHOOK_SECRET", "DIUN_WEBHOOK_SECRET"); x != "" {
		c.WebhookSecret = x
	}
	if x := firstEnv("COMPOSE_ROOT", "DOCKERUPBOT_COMPOSE_ROOT"); x != "" {
		c.Update.ComposeRoot = x
	}
	if x := firstEnv("TELEGRAM_CHAT_ID"); x != "" {
		if n, e := strconv.ParseInt(strings.TrimSpace(x), 10, 64); e == nil {
			c.Telegram.ChatID = n
		}
	}
	if x := firstEnv("ALLOWED_USERS", "DOCKERUPBOT_ALLOWED_USERS", "TELEGRAM_ALLOWED_USERS"); x != "" {
		c.Telegram.AllowedUsers = parseIntList(x)
	}
	if x := firstEnv("NOTIFY_EMPTY_SCAN", "DOCKERUPBOT_NOTIFY_EMPTY_SCAN"); x != "" {
		c.NotifyEmptyScan = parseBool(x)
	}
	if x := firstEnv("DIUN_CONTAINER", "DOCKERUPBOT_DIUN_CONTAINER"); x != "" {
		c.DiunContainer = x
	}
	if x := firstEnv("SKIP_IMAGES", "DOCKERUPBOT_SKIP_IMAGES"); x != "" {
		c.SkipImages = parseCSV(x)
	}
	if x := firstEnv("SKIP_CONTAINERS", "DOCKERUPBOT_SKIP_CONTAINERS"); x != "" {
		c.SkipContainers = parseCSV(x)
	}
	if x := firstEnv("QUIET_HOURS", "DOCKERUPBOT_QUIET_HOURS"); x != "" {
		c.QuietHours = x
	}
	if x := firstEnv("PRUNE_AFTER_SUCCESS", "DOCKERUPBOT_PRUNE_AFTER_SUCCESS"); x != "" {
		c.PruneAfterSuccess = parseBool(x)
	}
	if x := firstEnv("REQUIRE_HEALTHY", "DOCKERUPBOT_REQUIRE_HEALTHY"); x != "" {
		c.RequireHealthy = parseBool(x)
	}

	if c.Telegram.Token == "" {
		return c, fmt.Errorf("TELEGRAM_TOKEN is required")
	}
	if c.WebhookSecret == "" {
		return c, fmt.Errorf("WEBHOOK_SECRET is required")
	}
	if len(c.Telegram.AllowedUsers) == 0 && c.Telegram.ChatID == 0 {
		return c, fmt.Errorf("ALLOWED_USERS or TELEGRAM_CHAT_ID is required")
	}
	if c.QuietHours != "" {
		if _, _, err := ParseQuietHours(c.QuietHours); err != nil {
			return c, fmt.Errorf("quiet_hours: %w", err)
		}
	}
	return c, nil
}

func parseCSV(v string) []string {
	var out []string
	for _, s := range strings.Split(v, ",") {
		s = strings.TrimSpace(s)
		if s != "" {
			out = append(out, s)
		}
	}
	return out
}

func parseIntList(v string) []int64 {
	var out []int64
	for _, s := range strings.Split(v, ",") {
		n, e := strconv.ParseInt(strings.TrimSpace(s), 10, 64)
		if e == nil {
			out = append(out, n)
		}
	}
	return out
}

func parseBool(v string) bool {
	switch strings.ToLower(strings.TrimSpace(v)) {
	case "1", "true", "yes", "on":
		return true
	default:
		return false
	}
}

func firstEnv(keys ...string) string {
	for _, k := range keys {
		if x := os.Getenv(k); x != "" {
			return x
		}
	}
	return ""
}

func (c Config) NotifyTargets() []int64 {
	if c.Telegram.ChatID != 0 {
		return []int64{c.Telegram.ChatID}
	}
	return c.allowedUserTargets()
}

func (c Config) allowedUserTargets() []int64 {
	out := make([]int64, 0, len(c.Telegram.AllowedUsers))
	seen := map[int64]bool{}
	for _, u := range c.Telegram.AllowedUsers {
		if u == 0 || seen[u] {
			continue
		}
		seen[u] = true
		out = append(out, u)
	}
	return out
}

func (c *Config) SanitizeNotifyTargets(botID int64) (fixed bool) {
	if botID == 0 {
		return false
	}
	if c.Telegram.ChatID == botID {
		c.Telegram.ChatID = 0
		return true
	}
	filtered := c.Telegram.AllowedUsers[:0]
	for _, u := range c.Telegram.AllowedUsers {
		if u == botID {
			fixed = true
			continue
		}
		filtered = append(filtered, u)
	}
	c.Telegram.AllowedUsers = filtered
	return fixed
}

// ShouldSkip reports whether an image/container pair is excluded by policy.
func (c Config) ShouldSkip(image, container string) bool {
	for _, pat := range c.SkipImages {
		if matchPat(pat, image) {
			return true
		}
	}
	for _, pat := range c.SkipContainers {
		if matchPat(pat, container) {
			return true
		}
	}
	return false
}

func matchPat(pat, value string) bool {
	pat = strings.TrimSpace(pat)
	value = strings.TrimSpace(value)
	if pat == "" || value == "" {
		return false
	}
	if strings.HasPrefix(pat, "/") && strings.HasSuffix(pat, "/") && len(pat) > 2 {
		re, err := regexp.Compile(pat[1 : len(pat)-1])
		if err != nil {
			return false
		}
		return re.MatchString(value)
	}
	return strings.Contains(strings.ToLower(value), strings.ToLower(pat))
}

// ParseQuietHours parses "HH:MM-HH:MM" into start/end minutes from midnight.
func ParseQuietHours(s string) (startMin, endMin int, err error) {
	s = strings.TrimSpace(s)
	parts := strings.Split(s, "-")
	if len(parts) != 2 {
		return 0, 0, fmt.Errorf("want HH:MM-HH:MM, got %q", s)
	}
	startMin, err = parseClock(parts[0])
	if err != nil {
		return 0, 0, err
	}
	endMin, err = parseClock(parts[1])
	if err != nil {
		return 0, 0, err
	}
	return startMin, endMin, nil
}

func parseClock(s string) (int, error) {
	s = strings.TrimSpace(s)
	p := strings.Split(s, ":")
	if len(p) != 2 {
		return 0, fmt.Errorf("invalid time %q", s)
	}
	h, e1 := strconv.Atoi(p[0])
	m, e2 := strconv.Atoi(p[1])
	if e1 != nil || e2 != nil || h < 0 || h > 23 || m < 0 || m > 59 {
		return 0, fmt.Errorf("invalid time %q", s)
	}
	return h*60 + m, nil
}

// InQuietHours reports whether t falls inside configured quiet hours (supports overnight ranges).
func (c Config) InQuietHours(t time.Time) bool {
	if c.QuietHours == "" {
		return false
	}
	start, end, err := ParseQuietHours(c.QuietHours)
	if err != nil {
		return false
	}
	cur := t.Hour()*60 + t.Minute()
	if start == end {
		return false
	}
	if start < end {
		return cur >= start && cur < end
	}
	// Overnight e.g. 23:00-07:00
	return cur >= start || cur < end
}
